services:
   
  bb-db:
    image: be1en/bulletin-board-db:v5
    networks:
      - bb-net

  bb-app:
    image: be1en/bulletin-board-app:v5
    networks:
      - bb-net
    depends_on:
      - bb-db
    restart: on-failure

  bb-proxy:
    image: be1en/bulletin-board-proxy:v5
    ports:
      - "80:80"
    depends_on:
      - bb-app
    networks:
      - bb-net
    deploy:
      mode: replicated
      replicas: 3

  bb-metrics:
    image: be1en/bulletin-board-metrics:v5
    networks:
      - bb-net
    depends_on:
      - bb-app

  bb-dashboard:
    image: be1en/bulletin-board-dashboard:v5
    ports:
      - "3000:3000"
    depends_on:
      - bb-metrics
    networks:
      - bb-net

networks:
  bb-net:
